### ISSUE TITLE
Dynatrace Synthetic plugin DNS/Port/Ping no error condition handling

### ISSUE THREAD

**Issue by Randall526** [Dynatrace/dynatrace-api#45] opened 2021-02-27 01:06 UTC
We began to implement the ping/port plugin to resolve a problem with AIX agents that take a full 5 min of downtime to alert.  The majority of system cashes are rebooting in that time and not catching server outages.  Server availability shows 100% after the crash. The result is the unix team is not getting server down alerts, the applications see impact however the unix team needs these events to know a system went down.

We are using this plugin to address this however have the reverse problem with the plugin.  The plugin defaults to executing 1 min and does not allow for configuring the consecutive failures.  One ping or port failure keeps a problem open for 15 min.   We need the ability to make this less sensitive.  We've held off deploying port checks to the 5000 unix servers until this is resolved.  The current 100+ monitors sends about 10 alerts a day.

**Comment by myieye** [comment] 2021-04-15 06:30
Closed as duplicate of #44

**Closed** 2021-04-15 06:30 UTC
