### ISSUE TITLE
[Third-party synthetic] Port/Ping/DNS check, only option is to alert on the first failure

### ISSUE THREAD

**Issue by Randall526** [Dynatrace/dynatrace-api#44] opened 2021-02-27 01:01 UTC
We began to implement the ping/port plugin to resolve a problem with AIX agents that take a full 5 min of downtime to alert.  The majority of system cashes are rebooting in that time and not catching server outages.  Server availability shows 100% after the crash. The result is the unix team is not getting server down alerts, the applications see impact however the unix team needs these events to know a system went down.

We are using this plugin to address this however have the reverse problem with the plugin.  The plugin defaults to executing 1 min and does not allow for configuring the consecutive failures.  One ping or port failure keeps a problem open for 15 min.   We need the ability to make this less sensitive.  We've held off deploying port checks to the 5000 unix servers until this is resolved.  The current 100+ monitors sends about 10 alerts a day.

**Comment by myieye** [comment] 2021-03-04 11:12
@Randall526 thanks for reaching out.

Can you clarify the behaviour you'd like? Do you want:
1) The problem to only be open for 1 minute rather than 15 minutes (i.e. if one run fails, but the next run succeeds)
2) To only generate a problem if multiple runs fail in a row

I.e. which alerts do you **not** want to get?

**Comment by Randall526** [comment] 2021-03-04 15:00
Opening for 15 min is a little long, 10 min would work.  It's causing confusion for people not checking to see only one ping or port check failed.

The greater concern is the lack of failure options, either by default or a configurable option to alert after x consecutive failures is the primary issue.

**Comment by myieye** [comment] 2021-03-04 16:06
@Randall526 I'll do some digging around and get back to you soon.

**Comment by myieye** [comment] 2021-03-05 10:47
@Randall526

1) I can't reproduce problems staying open for 15 min if it fails for <15 min. The problem gets closed as soon as there's a successful execution.
2) @dlopes7 I think you'll have to take over for possibilities of configurable "failure options".
We don't plan to support it on the API side, so the viable options I see are:
- Managing it in the state of the extension/plugin
- (Adding an option for) not sending any events in the extension and then configuring alerts in Dynatrace based on availability

**Comment by dlopes7** [comment] 2021-03-06 14:59
We already send an "OK" event from the code when the test is successful, so the state is being managed from the extension.

@Randall526 can you please send a link to the tenant you are using to extensions@dynatrace.com so I can take a closer look at the behavior you are describing?

**Comment by dlopes7** [comment] 2021-03-06 15:01
I don't think adding consecutive failures control to the extension is a good idea because of the nature of the remote extension module, adding an option to not send events is a possibility though

**Comment by Randall526** [comment] 2021-03-07 22:20
Here's an example for a server that did not reboot but alerted for a failure in a single 1 min execution time slice.

Note how many availability events are registered for the single failure.

![image](https://user-images.githubusercontent.com/70070336/110256787-656a8600-7f60-11eb-93ae-2d64697f9e63.png)

![image](https://user-images.githubusercontent.com/70070336/110256840-ad89a880-7f60-11eb-88c6-4fbabdbba8e0.png)

We have a custom AIX extension we're going to roll out, I'm thinking of adding a uptime < 10 min check to it as a better means to detect reboots.   A system that stays down, should throw an availability alert from the agent.

**Comment by dlopes7** [comment] 2021-03-08 01:41
> Here's an example for a server that did not reboot but alerted for a failure in a single 1 min execution time slice.
> 
> 
> 
> Note how many availability events are registered for the single failure.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/70070336/110256964-4c160980-7f61-11eb-8995-c3db32658b91.png)
> 
> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/70070336/110256938-27219680-7f61-11eb-9509-3bd0c62b6272.png)
> 
> 
> 
> 
> 
> We have a custom AIX extension we're going to roll out, I'm thinking of adding a uptime < 10 min check to it as a better means to detect reboots.   A system that stays down, should throw an availability alert from the agent.
> 
> 

This metric/event on the screenshot is not coming from this extension, it shows a Custom Device, not a synthetic test, I am not sure I follow

**Comment by Randall526** [comment] 2021-03-08 18:16
Solid point, it occurred to me we are using the old plugin for some of these checks still.  My Fault,  I don't have a good example for the new plugin that registers as a synthetic. 

Before testing on a larger scale, can we confirm the failure handling is different or improved with the synthetic extension?

**Comment by dlopes7** [comment] 2021-03-08 22:44
That is correct, the extension framework behaves as you described, alerts have a default timeout of 15 minutes and that is why the problem remains opened for so long.

The good news is that this extension uses the synthetic tests api, which means we can send resolved events as soon as the test works again and the problem is closed, no timeouts are involved

**Comment by Randall526** [comment] 2021-03-24 22:15
HEy there, meant to reply sooner.

So the synthetic API resolves sooner which is good.  Is there any difference in logic to not alert on the first port or ping failure with the newer github plugin>  As far as I can tell, it alerts on it's own with no settings.  I'm curios if the logic under the hood is a little less sensitive on the new plugin.   We still have the older TCPsocket plugin in use on a larger scale vs the new one.

**Comment by dlopes7** [comment] 2021-03-25 00:49
There is no logic at all today, if the ping fails we immediately send the event to Dynatrace

Feel free to modify the source code if you want to alert after multiple failures, this repo is an example to be extended, not a supported extension

**Comment by myieye** [comment] 2021-05-07 08:37
@dlopes7 was this fixed/added in #54? Can we close this?

**Closed** 2021-05-10 06:13 UTC
